#!/bin/bash

rm -rf bin && mkdir bin

GOOS=linux    GOARCH=amd64  go build -o bin/hnwelcome-linux-amd64 .
GOOS=linux    GOARCH=arm64  go build -o bin/hnwelcome-linux-arm64 .
GOOS=darwin   GOARCH=amd64  go build -o bin/hnwelcome-mac-amd64 .
GOOS=darwin   GOARCH=arm64  go build -o bin/hnwelcome-mac-arm64 .
GOOS=windows  GOARCH=amd64  go build -o bin/hnwelcome-win-amd64.exe .
GOOS=windows  GOARCH=arm64  go build -o bin/hnwelcome-win-arm64.exe .
